name: Run Stock Check

on:
  workflow_dispatch: # 可手動觸發
  schedule:
    - cron: '0 0 * * 0' # 每週日午夜執行（UTC時間）

jobs:
  build:
    runs-on: windows-latest  # 這裡建議使用windows-latest（因你的程式是Windows路徑）
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install yfinance pandas

      - name: Run stock checker
        run: python buystock.py

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: qualified_stocks
          path: qualified_stocks.csv
